// ─── Product Catalog ───────────────────────────────────────────
// 50 curated products across 5 categories

const CATEGORIES = [
  { id: 'all', name: 'All', emoji: '✨', gradient: 'linear-gradient(135deg, #a855f7, #06b6d4)' },
  { id: 'electronics', name: 'Electronics', emoji: '💻', gradient: 'linear-gradient(135deg, #6366f1, #8b5cf6)' },
  { id: 'fashion', name: 'Fashion', emoji: '👗', gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)' },
  { id: 'home', name: 'Home & Kitchen', emoji: '🏠', gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)' },
  { id: 'sports', name: 'Sports & Outdoors', emoji: '⚽', gradient: 'linear-gradient(135deg, #10b981, #14b8a6)' },
  { id: 'beauty', name: 'Beauty & Care', emoji: '✨', gradient: 'linear-gradient(135deg, #f472b6, #c084fc)' },
];

const PRODUCTS = [
  // ── Electronics (10) ──────────────────────
  {
    id: 1,
    name: 'MacBook Pro 14"',
    category: 'electronics',
    price: 169900,
    originalPrice: 189900,
    rating: 4.8,
    reviews: 2453,
    description: 'Apple M3 Pro chip, 18GB RAM, 512GB SSD. Stunning Liquid Retina XDR display with ProMotion. Up to 17 hours of battery life.',
    emoji: '💻',
    gradient: 'linear-gradient(135deg, #374151, #1f2937)',
    tags: ['laptop', 'apple', 'macbook', 'pro', 'work', 'coding', 'programming', 'professional'],
    badge: 'Best Seller'
  },
  {
    id: 2,
    name: 'Sony WH-1000XM5',
    category: 'electronics',
    price: 29990,
    originalPrice: 34990,
    rating: 4.7,
    reviews: 8921,
    description: 'Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling. 30-hour battery life.',
    emoji: '🎧',
    gradient: 'linear-gradient(135deg, #1e3a5f, #0d1b2a)',
    tags: ['headphones', 'sony', 'noise cancelling', 'wireless', 'bluetooth', 'music', 'audio'],
    badge: 'Top Rated'
  },
  {
    id: 3,
    name: 'iPhone 16 Pro Max',
    category: 'electronics',
    price: 144900,
    originalPrice: 144900,
    rating: 4.9,
    reviews: 5672,
    description: 'A18 Pro chip, 48MP camera system with 5x Telephoto. Titanium design. Action button. All-day battery life.',
    emoji: '📱',
    gradient: 'linear-gradient(135deg, #4a3728, #2d1f14)',
    tags: ['phone', 'iphone', 'apple', 'smartphone', 'camera', 'mobile'],
    badge: 'New'
  },
  {
    id: 4,
    name: 'Samsung Galaxy S24 Ultra',
    category: 'electronics',
    price: 129999,
    originalPrice: 139999,
    rating: 4.7,
    reviews: 3891,
    description: 'Galaxy AI built in. 200MP camera. Titanium frame with embedded S Pen. QHD+ Dynamic AMOLED 2X display.',
    emoji: '📱',
    gradient: 'linear-gradient(135deg, #4a1a6b, #2d1040)',
    tags: ['phone', 'samsung', 'galaxy', 'android', 'smartphone', 'camera', 's pen'],
    badge: null
  },
  {
    id: 5,
    name: 'iPad Air M2',
    category: 'electronics',
    price: 59900,
    originalPrice: 64900,
    rating: 4.8,
    reviews: 1876,
    description: 'M2 chip. 11-inch Liquid Retina display. Works with Apple Pencil Pro and Magic Keyboard. All-day battery.',
    emoji: '📲',
    gradient: 'linear-gradient(135deg, #1e40af, #1e3a8a)',
    tags: ['tablet', 'ipad', 'apple', 'drawing', 'portable', 'study'],
    badge: null
  },
  {
    id: 6,
    name: 'Sony A7 IV Camera',
    category: 'electronics',
    price: 219990,
    originalPrice: 239990,
    rating: 4.9,
    reviews: 1245,
    description: '33MP full-frame sensor. 4K 60p video. Real-time Eye AF for humans, animals, and birds. 10fps burst shooting.',
    emoji: '📷',
    gradient: 'linear-gradient(135deg, #1a1a2e, #16213e)',
    tags: ['camera', 'sony', 'photography', 'mirrorless', 'full frame', 'video', 'professional'],
    badge: 'Pro Choice'
  },
  {
    id: 7,
    name: 'Apple Watch Ultra 2',
    category: 'electronics',
    price: 79900,
    originalPrice: 89900,
    rating: 4.7,
    reviews: 2134,
    description: '49mm titanium case. Brightest Apple display ever at 3000 nits. Precision dual-frequency GPS. 36-hour battery.',
    emoji: '⌚',
    gradient: 'linear-gradient(135deg, #b45309, #78350f)',
    tags: ['watch', 'smartwatch', 'apple', 'fitness', 'gps', 'health tracking'],
    badge: null
  },
  {
    id: 8,
    name: 'Dell UltraSharp 27" 4K Monitor',
    category: 'electronics',
    price: 54990,
    originalPrice: 62990,
    rating: 4.6,
    reviews: 987,
    description: 'IPS Black technology for deeper blacks. USB-C hub with 90W power delivery. 99% sRGB, 98% DCI-P3 color accuracy.',
    emoji: '🖥️',
    gradient: 'linear-gradient(135deg, #0f172a, #1e293b)',
    tags: ['monitor', 'dell', '4k', 'display', 'work', 'usb-c', 'professional'],
    badge: 'Editor Pick'
  },
  {
    id: 9,
    name: 'Bose QuietComfort Earbuds II',
    category: 'electronics',
    price: 24900,
    originalPrice: 26900,
    rating: 4.6,
    reviews: 4532,
    description: 'CustomTune sound calibration. World-class noise cancellation. 6 hours playtime plus 18 hours with case. IPX4 rated.',
    emoji: '🎵',
    gradient: 'linear-gradient(135deg, #1e293b, #334155)',
    tags: ['earbuds', 'bose', 'noise cancelling', 'wireless', 'bluetooth', 'music'],
    badge: null
  },
  {
    id: 10,
    name: 'Nintendo Switch OLED',
    category: 'electronics',
    price: 31990,
    originalPrice: 34990,
    rating: 4.8,
    reviews: 7654,
    description: '7-inch OLED screen with vivid colors. Wide adjustable stand. 64GB internal storage. Enhanced audio.',
    emoji: '🎮',
    gradient: 'linear-gradient(135deg, #dc2626, #1d4ed8)',
    tags: ['gaming', 'nintendo', 'console', 'portable', 'games', 'gift'],
    badge: 'Great Gift'
  },

  // ── Fashion (10) ──────────────────────────
  {
    id: 11,
    name: 'Nike Air Max 90',
    category: 'fashion',
    price: 10995,
    originalPrice: 12995,
    rating: 4.7,
    reviews: 12453,
    description: 'Iconic waffle outsole, stitched overlays, and TPU accents. Max Air cushioning for all-day comfort.',
    emoji: '👟',
    gradient: 'linear-gradient(135deg, #dc2626, #991b1b)',
    tags: ['shoes', 'nike', 'sneakers', 'running', 'casual', 'air max', 'athletic'],
    badge: 'Iconic'
  },
  {
    id: 12,
    name: 'Levi\'s Trucker Jacket',
    category: 'fashion',
    price: 4999,
    originalPrice: 6599,
    rating: 4.5,
    reviews: 3456,
    description: 'Classic denim jacket in non-stretch cotton. Button front closure. Adjustable waistband tabs. Two chest pockets.',
    emoji: '🧥',
    gradient: 'linear-gradient(135deg, #1e40af, #1e3a8a)',
    tags: ['jacket', 'levis', 'denim', 'casual', 'classic', 'outerwear'],
    badge: null
  },
  {
    id: 13,
    name: 'Ray-Ban Wayfarer Classic',
    category: 'fashion',
    price: 9990,
    originalPrice: 11590,
    rating: 4.8,
    reviews: 8976,
    description: 'The most recognizable style in sunglasses. Full rim acetate frame with crystal green G-15 lenses. 100% UV protection.',
    emoji: '🕶️',
    gradient: 'linear-gradient(135deg, #1f2937, #111827)',
    tags: ['sunglasses', 'ray-ban', 'wayfarer', 'accessories', 'summer', 'uv protection'],
    badge: 'Classic'
  },
  {
    id: 14,
    name: 'Adidas Ultraboost 23',
    category: 'fashion',
    price: 15999,
    originalPrice: 17999,
    rating: 4.7,
    reviews: 5643,
    description: 'BOOST midsole for incredible energy return. Primeknit+ upper for adaptive fit. Continental rubber outsole.',
    emoji: '👟',
    gradient: 'linear-gradient(135deg, #111827, #374151)',
    tags: ['shoes', 'adidas', 'running', 'ultraboost', 'athletic', 'comfortable'],
    badge: null
  },
  {
    id: 15,
    name: 'Coach Willow Tote Bag',
    category: 'fashion',
    price: 34900,
    originalPrice: 39900,
    rating: 4.6,
    reviews: 2341,
    description: 'Polished pebble leather. Detachable zip pouch. Shoulder straps with 10.5" drop. Snap closure. Interior zip pocket.',
    emoji: '👜',
    gradient: 'linear-gradient(135deg, #92400e, #78350f)',
    tags: ['bag', 'coach', 'tote', 'leather', 'handbag', 'luxury', 'work'],
    badge: null
  },
  {
    id: 16,
    name: 'Casio G-Shock GA-2100',
    category: 'fashion',
    price: 8995,
    originalPrice: 9995,
    rating: 4.8,
    reviews: 6789,
    description: 'Carbon Core Guard structure. Shock-resistant. 200M water resistance. World time. Stopwatch. LED light.',
    emoji: '⌚',
    gradient: 'linear-gradient(135deg, #1a1a2e, #0f0f23)',
    tags: ['watch', 'casio', 'g-shock', 'durable', 'waterproof', 'sport'],
    badge: 'Hot'
  },
  {
    id: 17,
    name: 'North Face Nuptse Jacket',
    category: 'fashion',
    price: 26990,
    originalPrice: 29990,
    rating: 4.7,
    reviews: 4567,
    description: '700-fill goose down insulation. DWR finish. Stowable in its own pocket. Elastic cuffs and hem. Iconic baffles.',
    emoji: '🧥',
    gradient: 'linear-gradient(135deg, #1e3a5f, #0d1b2a)',
    tags: ['jacket', 'north face', 'puffer', 'winter', 'warm', 'down', 'outerwear'],
    badge: 'Winter Essential'
  },
  {
    id: 18,
    name: 'Converse Chuck Taylor All Star',
    category: 'fashion',
    price: 4499,
    originalPrice: 5299,
    rating: 4.6,
    reviews: 15678,
    description: 'Canvas upper. Ortholite insole for cushioning. Vulcanized rubber outsole. The original basketball shoe since 1917.',
    emoji: '👟',
    gradient: 'linear-gradient(135deg, #dc2626, #f8f8f8)',
    tags: ['shoes', 'converse', 'sneakers', 'casual', 'classic', 'canvas', 'affordable'],
    badge: 'Under ₹5,000'
  },
  {
    id: 19,
    name: 'Polo Ralph Lauren Oxford Shirt',
    category: 'fashion',
    price: 8990,
    originalPrice: 10500,
    rating: 4.5,
    reviews: 3214,
    description: 'Classic fit. Button-down collar. Signature embroidered pony. Shirttail hem. Premium cotton oxford cloth.',
    emoji: '👔',
    gradient: 'linear-gradient(135deg, #1e3a5f, #1e40af)',
    tags: ['shirt', 'ralph lauren', 'polo', 'formal', 'casual', 'cotton', 'classic'],
    badge: null
  },
  {
    id: 20,
    name: 'Fjällräven Kånken Backpack',
    category: 'fashion',
    price: 6999,
    originalPrice: 7999,
    rating: 4.7,
    reviews: 9876,
    description: 'Vinylon F fabric. Dual top handles and adjustable shoulder straps. Zip opening to main compartment. Front zip pocket.',
    emoji: '🎒',
    gradient: 'linear-gradient(135deg, #b91c1c, #dc2626)',
    tags: ['backpack', 'fjallraven', 'bag', 'school', 'travel', 'iconic', 'durable'],
    badge: 'Trending'
  },

  // ── Home & Kitchen (10) ───────────────────
  {
    id: 21,
    name: 'Nespresso Vertuo Next',
    category: 'home',
    price: 16990,
    originalPrice: 19990,
    rating: 4.5,
    reviews: 6543,
    description: 'Centrifusion technology for barista-quality coffee. 5 cup sizes from espresso to alto. WiFi connectivity for updates.',
    emoji: '☕',
    gradient: 'linear-gradient(135deg, #78350f, #451a03)',
    tags: ['coffee', 'nespresso', 'espresso', 'kitchen', 'appliance', 'barista'],
    badge: 'Best Seller'
  },
  {
    id: 22,
    name: 'Dyson V15 Detect',
    category: 'home',
    price: 65900,
    originalPrice: 74900,
    rating: 4.8,
    reviews: 3421,
    description: 'Laser reveals microscopic dust. Piezo sensor counts particles. LCD screen shows real-time data. Up to 60 min runtime.',
    emoji: '🧹',
    gradient: 'linear-gradient(135deg, #7c3aed, #6d28d9)',
    tags: ['vacuum', 'dyson', 'cleaning', 'cordless', 'smart', 'home'],
    badge: 'Premium'
  },
  {
    id: 23,
    name: 'Amazon Echo Show 10',
    category: 'home',
    price: 24999,
    originalPrice: 27999,
    rating: 4.4,
    reviews: 4567,
    description: '10.1" HD screen that moves with you. Smart home hub with Zigbee. 13MP camera with auto-framing for video calls.',
    emoji: '📺',
    gradient: 'linear-gradient(135deg, #0369a1, #0284c7)',
    tags: ['smart speaker', 'alexa', 'echo', 'smart home', 'display', 'voice assistant'],
    badge: null
  },
  {
    id: 24,
    name: 'KitchenAid Artisan Stand Mixer',
    category: 'home',
    price: 49990,
    originalPrice: 54990,
    rating: 4.9,
    reviews: 11234,
    description: '5-quart stainless steel bowl. 10 speeds. Tilt-head design. 59-point planetary mixing action. 15+ optional attachments.',
    emoji: '🍰',
    gradient: 'linear-gradient(135deg, #dc2626, #b91c1c)',
    tags: ['mixer', 'kitchenaid', 'baking', 'cooking', 'kitchen', 'appliance'],
    badge: 'Top Rated'
  },
  {
    id: 25,
    name: 'Philips Hue Starter Kit',
    category: 'home',
    price: 14999,
    originalPrice: 17999,
    rating: 4.6,
    reviews: 7890,
    description: '4 A19 smart bulbs + Hue Bridge. 16 million colors. Voice control with Alexa/Google. Schedules and automations.',
    emoji: '💡',
    gradient: 'linear-gradient(135deg, #eab308, #f59e0b)',
    tags: ['lights', 'smart home', 'philips', 'hue', 'led', 'ambiance', 'automation'],
    badge: null
  },
  {
    id: 26,
    name: 'Le Creuset Dutch Oven 5.5 Qt',
    category: 'home',
    price: 36990,
    originalPrice: 39990,
    rating: 4.9,
    reviews: 5678,
    description: 'Enameled cast iron. Superior heat distribution. Colorful exterior enamel resists chipping. Oven safe to 500°F.',
    emoji: '🍲',
    gradient: 'linear-gradient(135deg, #ea580c, #c2410c)',
    tags: ['cookware', 'le creuset', 'dutch oven', 'cast iron', 'cooking', 'kitchen'],
    badge: 'Heirloom'
  },
  {
    id: 27,
    name: 'iRobot Roomba j7+',
    category: 'home',
    price: 54900,
    originalPrice: 62900,
    rating: 4.5,
    reviews: 3456,
    description: 'PrecisionVision Navigation avoids obstacles. Self-emptying base. Smart mapping learns your home. Works with Alexa.',
    emoji: '🤖',
    gradient: 'linear-gradient(135deg, #374151, #1f2937)',
    tags: ['robot vacuum', 'roomba', 'cleaning', 'smart home', 'automatic', 'ai'],
    badge: 'Smart Home'
  },
  {
    id: 28,
    name: 'Vitamix E310 Explorian Blender',
    category: 'home',
    price: 34990,
    originalPrice: 39990,
    rating: 4.7,
    reviews: 4321,
    description: '2.0 HP motor. Variable speed control + pulse. 48 oz container. Self-cleaning in 60 seconds. Aircraft-grade blades.',
    emoji: '🥤',
    gradient: 'linear-gradient(135deg, #1f2937, #111827)',
    tags: ['blender', 'vitamix', 'smoothie', 'kitchen', 'cooking', 'health'],
    badge: null
  },
  {
    id: 29,
    name: 'Casper Original Mattress (Queen)',
    category: 'home',
    price: 89900,
    originalPrice: 99900,
    rating: 4.5,
    reviews: 8765,
    description: 'Zoned Support for perfect alignment. AirScape perforated foam for cool sleep. 100-night trial. 10-year warranty.',
    emoji: '🛏️',
    gradient: 'linear-gradient(135deg, #6366f1, #818cf8)',
    tags: ['mattress', 'casper', 'sleep', 'bedroom', 'foam', 'comfort'],
    badge: '100-Night Trial'
  },
  {
    id: 30,
    name: 'Breville Barista Express',
    category: 'home',
    price: 64990,
    originalPrice: 69990,
    rating: 4.6,
    reviews: 5432,
    description: 'Integrated conical burr grinder. Digital temperature control. Steam wand for micro-foam milk. 2-cup capacity.',
    emoji: '☕',
    gradient: 'linear-gradient(135deg, #78716c, #57534e)',
    tags: ['espresso', 'coffee', 'breville', 'barista', 'grinder', 'kitchen'],
    badge: 'Barista Grade'
  },

  // ── Sports & Outdoors (10) ────────────────
  {
    id: 31,
    name: 'Nike Pegasus 41',
    category: 'sports',
    price: 11895,
    originalPrice: 13495,
    rating: 4.7,
    reviews: 8765,
    description: 'ReactX foam delivers 13% more energy return. Flywire cables lock you in. Waffle outsole for traction on any surface.',
    emoji: '🏃',
    gradient: 'linear-gradient(135deg, #059669, #047857)',
    tags: ['running shoes', 'nike', 'pegasus', 'athletic', 'marathon', 'training'],
    badge: 'Runner Fav'
  },
  {
    id: 32,
    name: 'Garmin Forerunner 265',
    category: 'sports',
    price: 43990,
    originalPrice: 47990,
    rating: 4.8,
    reviews: 2345,
    description: 'AMOLED touchscreen. Training readiness + race predictor. Multi-band GPS. 13-day battery life. Music storage.',
    emoji: '⌚',
    gradient: 'linear-gradient(135deg, #0d9488, #0f766e)',
    tags: ['fitness tracker', 'garmin', 'gps', 'running', 'watch', 'training', 'health'],
    badge: 'Top Rated'
  },
  {
    id: 33,
    name: 'Manduka PRO Yoga Mat',
    category: 'sports',
    price: 9999,
    originalPrice: 11499,
    rating: 4.8,
    reviews: 6543,
    description: '6mm thick closed-cell surface. Dense cushioning for joint protection. Lifetime guarantee. Non-toxic, emissions-free.',
    emoji: '🧘',
    gradient: 'linear-gradient(135deg, #7c3aed, #6d28d9)',
    tags: ['yoga', 'mat', 'manduka', 'fitness', 'exercise', 'stretching'],
    badge: 'Lifetime Warranty'
  },
  {
    id: 34,
    name: 'Hydro Flask 32oz Wide Mouth',
    category: 'sports',
    price: 3499,
    originalPrice: 3999,
    rating: 4.7,
    reviews: 15432,
    description: 'TempShield double-wall vacuum insulation. Keeps drinks cold 24h, hot 12h. Durable powder coat. BPA-free.',
    emoji: '🧊',
    gradient: 'linear-gradient(135deg, #0ea5e9, #0284c7)',
    tags: ['water bottle', 'hydro flask', 'insulated', 'outdoor', 'hydration', 'gym'],
    badge: 'Under ₹4,000'
  },
  {
    id: 35,
    name: 'Theragun Elite Massager',
    category: 'sports',
    price: 34990,
    originalPrice: 38990,
    rating: 4.7,
    reviews: 3456,
    description: 'QuietForce Technology. 5 built-in speeds. OLED screen. Bluetooth app integration. 120-minute battery. Ergonomic design.',
    emoji: '💪',
    gradient: 'linear-gradient(135deg, #1f2937, #111827)',
    tags: ['massage', 'recovery', 'theragun', 'muscle', 'therapy', 'fitness'],
    badge: null
  },
  {
    id: 36,
    name: 'Osprey Atmos AG 65 Backpack',
    category: 'sports',
    price: 27990,
    originalPrice: 31990,
    rating: 4.8,
    reviews: 2678,
    description: 'Anti-Gravity suspension system. Fully adjustable harness and hipbelt. Integrated raincover. Stow-on-the-Go trekking pole.',
    emoji: '🎒',
    gradient: 'linear-gradient(135deg, #065f46, #064e3b)',
    tags: ['backpack', 'osprey', 'hiking', 'camping', 'trekking', 'travel', 'outdoor'],
    badge: 'Award Winner'
  },
  {
    id: 37,
    name: 'YETI Tundra 45 Cooler',
    category: 'sports',
    price: 29990,
    originalPrice: 32990,
    rating: 4.7,
    reviews: 4321,
    description: 'Rotomolded construction. PermaFrost insulation. Bear-proof certified. Non-slip feet. Dry goods basket included.',
    emoji: '🧊',
    gradient: 'linear-gradient(135deg, #e5e7eb, #9ca3af)',
    tags: ['cooler', 'yeti', 'outdoor', 'camping', 'ice', 'durable', 'picnic'],
    badge: 'Indestructible'
  },
  {
    id: 38,
    name: 'Fitbit Charge 6',
    category: 'sports',
    price: 14999,
    originalPrice: 16999,
    rating: 4.5,
    reviews: 5678,
    description: 'Built-in GPS. Stress management score. SpO2. Skin temperature sensor. Google integration. 7-day battery.',
    emoji: '⌚',
    gradient: 'linear-gradient(135deg, #374151, #4b5563)',
    tags: ['fitness tracker', 'fitbit', 'health', 'steps', 'heart rate', 'sleep tracking'],
    badge: null
  },
  {
    id: 39,
    name: 'Coleman Sundome 4-Person Tent',
    category: 'sports',
    price: 7999,
    originalPrice: 9499,
    rating: 4.4,
    reviews: 8765,
    description: 'WeatherTec system with welded floors. Snag-free poles. Setup in 10 minutes. Large windows and ground vent.',
    emoji: '⛺',
    gradient: 'linear-gradient(135deg, #16a34a, #15803d)',
    tags: ['tent', 'camping', 'coleman', 'outdoor', 'hiking', 'family', 'affordable'],
    badge: 'Budget Pick'
  },
  {
    id: 40,
    name: 'Bowflex SelectTech 552 Dumbbells',
    category: 'sports',
    price: 39990,
    originalPrice: 47990,
    rating: 4.7,
    reviews: 7654,
    description: 'Replace 15 sets of weights. Adjustable from 5 to 52.5 lbs. Quick dial system. Compact storage. Durable molding.',
    emoji: '🏋️',
    gradient: 'linear-gradient(135deg, #b91c1c, #991b1b)',
    tags: ['dumbbells', 'bowflex', 'weights', 'home gym', 'strength', 'adjustable', 'workout'],
    badge: 'Space Saver'
  },

  // ── Beauty & Personal Care (10) ───────────
  {
    id: 41,
    name: 'Dyson Airwrap Multi-Styler',
    category: 'beauty',
    price: 49900,
    originalPrice: 54900,
    rating: 4.6,
    reviews: 4567,
    description: 'Coanda airflow styles and dries simultaneously. 6 attachments for curls, waves, and smooth blowouts. No extreme heat.',
    emoji: '💇',
    gradient: 'linear-gradient(135deg, #be185d, #9d174d)',
    tags: ['hair styler', 'dyson', 'airwrap', 'curling', 'blowout', 'hair care'],
    badge: 'Cult Favorite'
  },
  {
    id: 42,
    name: 'La Mer Moisturizing Cream',
    category: 'beauty',
    price: 18500,
    originalPrice: 20500,
    rating: 4.8,
    reviews: 3456,
    description: 'Cell-renewing Miracle Broth. Ultra-rich cream softens, smooths, and helps heal dryness. 1 oz jar.',
    emoji: '✨',
    gradient: 'linear-gradient(135deg, #0d9488, #0f766e)',
    tags: ['skincare', 'la mer', 'moisturizer', 'luxury', 'cream', 'anti-aging'],
    badge: 'Luxury'
  },
  {
    id: 43,
    name: 'Charlotte Tilbury Pillow Talk Set',
    category: 'beauty',
    price: 6490,
    originalPrice: 7990,
    rating: 4.7,
    reviews: 8765,
    description: 'Iconic lip kit including Matte Revolution lipstick and Lip Cheat liner in universally flattering Pillow Talk shade.',
    emoji: '💄',
    gradient: 'linear-gradient(135deg, #f472b6, #ec4899)',
    tags: ['lipstick', 'charlotte tilbury', 'makeup', 'lips', 'gift set', 'pillow talk'],
    badge: 'Iconic'
  },
  {
    id: 44,
    name: 'Olaplex Hair Repair Treatment Set',
    category: 'beauty',
    price: 7490,
    originalPrice: 8990,
    rating: 4.6,
    reviews: 6543,
    description: 'No.3 Hair Perfector + No.4 Bond Maintenance Shampoo + No.5 Conditioner. Repairs and strengthens damaged hair.',
    emoji: '💆',
    gradient: 'linear-gradient(135deg, #c084fc, #a855f7)',
    tags: ['hair care', 'olaplex', 'repair', 'shampoo', 'treatment', 'damaged hair'],
    badge: null
  },
  {
    id: 45,
    name: 'Drunk Elephant Protini Moisturizer',
    category: 'beauty',
    price: 5990,
    originalPrice: 6500,
    rating: 4.5,
    reviews: 5432,
    description: 'Protein peptide moisturizer with signal peptides, growth factors, and amino acids. Improves firmness and tone.',
    emoji: '🧴',
    gradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
    tags: ['skincare', 'drunk elephant', 'moisturizer', 'peptide', 'anti-aging', 'clean beauty'],
    badge: 'Clean Beauty'
  },
  {
    id: 46,
    name: 'Tom Ford Oud Wood Eau de Parfum',
    category: 'beauty',
    price: 22900,
    originalPrice: 25900,
    rating: 4.8,
    reviews: 2345,
    description: 'Exotic smoky woods and rare oud. Notes of rosewood, cardamom, sandalwood, and amber. 50ml bottle.',
    emoji: '🌹',
    gradient: 'linear-gradient(135deg, #451a03, #78350f)',
    tags: ['fragrance', 'tom ford', 'perfume', 'oud', 'luxury', 'cologne', 'gift'],
    badge: 'Signature'
  },
  {
    id: 47,
    name: 'Foreo Luna 4 Face Cleanser',
    category: 'beauty',
    price: 24900,
    originalPrice: 27900,
    rating: 4.6,
    reviews: 3456,
    description: 'T-Sonic pulsations for deep cleansing. Firming massage mode. 100% waterproof. App-connected. Lasts 4 months per charge.',
    emoji: '🫧',
    gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)',
    tags: ['skincare', 'foreo', 'cleanser', 'device', 'facial', 'cleansing brush'],
    badge: null
  },
  {
    id: 48,
    name: 'Tatcha Dewy Skin Cream',
    category: 'beauty',
    price: 5990,
    originalPrice: 6990,
    rating: 4.7,
    reviews: 4321,
    description: 'Rich cream with Japanese purple rice, Okinawa algae, and hyaluronic acid. Plumps and hydrates for dewy glow.',
    emoji: '💎',
    gradient: 'linear-gradient(135deg, #7c3aed, #6d28d9)',
    tags: ['skincare', 'tatcha', 'moisturizer', 'japanese', 'hydrating', 'luxury'],
    badge: 'J-Beauty'
  },
  {
    id: 49,
    name: 'Philips Sonicare DiamondClean',
    category: 'beauty',
    price: 18990,
    originalPrice: 21990,
    rating: 4.6,
    reviews: 7654,
    description: '5 brushing modes. 62,000 brush movements/min. Premium glass charging cup. USB travel case. 2-week battery.',
    emoji: '🪥',
    gradient: 'linear-gradient(135deg, #f8fafc, #cbd5e1)',
    tags: ['toothbrush', 'philips', 'sonicare', 'oral care', 'electric', 'dental'],
    badge: 'Dentist Rec'
  },
  {
    id: 50,
    name: 'GHD Platinum+ Styler',
    category: 'beauty',
    price: 24900,
    originalPrice: 26900,
    rating: 4.7,
    reviews: 5678,
    description: 'Predictive ultra-zone technology adapts heat for healthier hair. Universal voltage. Sleep mode. Wishbone hinge.',
    emoji: '💇',
    gradient: 'linear-gradient(135deg, #1f2937, #111827)',
    tags: ['hair straightener', 'ghd', 'flat iron', 'hair styling', 'heat protection'],
    badge: 'Pro Grade'
  }
];

// Utility: search products by query
function searchProducts(query) {
  if (!query) return PRODUCTS;
  const q = query.toLowerCase().trim();
  return PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.tags.some(t => t.includes(q))
  );
}

// Utility: get products by category
function getProductsByCategory(categoryId) {
  if (categoryId === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === categoryId);
}

// Utility: get product by ID
function getProductById(id) {
  return PRODUCTS.find(p => p.id === id);
}

// Utility: get catalog summary for AI context
function getCatalogSummary() {
  return PRODUCTS.map(p =>
    `[ID:${p.id}] ${p.name} — ₹${p.price.toLocaleString('en-IN')} | ${p.category} | ★${p.rating} (${p.reviews} reviews) | ${p.description}`
  ).join('\n');
}
